version: '3.8'

services:
  backend:
    image: larguma/goblinzbot:latest
    container_name: goblinzbot_backend
    restart: always
    volumes:
      - /home/larguma/docker_data/cal-discord-bot/appsettings.json:/app/appsettings.json
    depends_on:
      - db

  db:
    image: mongo
    container_name: goblinzbot_db
    restart: always
    volumes:
      - db-data:/var/lib/mongodb

volumes:
  db-data: